# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/at1600/xiaomi_kernel_odin_x
          kernel-dir: msm-5.4
          kernel-branch: main
          config: odin_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: false
          android-version: 34
          aosp-clang-version: r450784d
          disable-lto: true
          anykernel3: true
